Petrack
JuPedSim/jpsvis pull request #130
Opened 2022-01-08 11:18 UTC by chraibi

Address issue #120. 

Convert [Petrack-files](https://ped.fz-juelich.de/db) to a JuPedSim-compatible [format](https://www.jupedsim.org/jpscore_trajectory.html#default-output).

TODO: 
- [ ] some petrack files do not have a header
- [ ] something is wrong with "Crowds in front of bottlenecks from the perspective of physics and social psychology". Check.

Example: Bottleneck and social groups

```
 python ~/workspace/jupedsim/jpsvis/scripts/petrack2jpsvis.py -f 00_08.txt --df  10
```

<img width="505" alt="Screen Shot 2022-01-08 at 12 16 34" src="https://user-images.githubusercontent.com/5772973/148642070-67a69bce-637c-4e80-8f75-babce2f9a228.png">

2022-01-10 11:40 UTC, Ozaq requested changes
Additionally please use 'snake case' naming as described in PEP-8 for variables, see https://www.python.org/dev/peps/pep-0008/#type-variable-names

2022-01-10 14:36 UTC, chraibi commented on scripts/petrack2jpsvis.py
> +    New columns are added (A, B, ANGLE, COLOR)
+1

2022-01-10 15:03 UTC, chraibi reviewed
deal with Kai's comments.

2022-01-10 15:03 UTC, chraibi commented on scripts/petrack2jpsvis.py
> +        sys.exit()
+1

2022-01-11 14:44 UTC, Ozaq requested changes

2022-01-11 14:44 UTC, Ozaq commented on scripts/petrack2jpsvis.py
> +    return (Speed, Angle)
`Size`, `Angle`, `Speed` etc... are not conforming to PEP-8 naming, i.e. snake_case.

2022-01-11 14:44 UTC, Ozaq commented on scripts/petrack2jpsvis.py
> +                raise Exception(f"Trajectory is malformed: {err}") from err
Why are you re-raising the exception but to catching it? The outer try/except is only acting on OSError. Like this it will bubble up to past main and exit the process with a python stack trace. I think you intended to handle the Exception in the outer `except` block

2022-01-11 14:56 UTC, chraibi commented on scripts/petrack2jpsvis.py
> +    return (Speed, Angle)
+1

2022-01-11 14:56 UTC, chraibi commented on scripts/petrack2jpsvis.py
> +                raise Exception(f"Trajectory is malformed: {err}") from err
+1

2022-01-11 15:03 UTC, Ozaq approved these changes

2022-01-11 15:13 UTC, merged