Rework VTK rendering integration & simplify UI
JuPedSim/jpsvis pull request #96
Opened 2021-09-24 12:55 UTC by Ozaq

There are still several rendering issues and rance conditions lurking,
but right now this should already improve the situation quite a bit.

2021-09-24 13:57 UTC, schroedtert commented on src/InteractorStyle.h
> +#pragma once
Will this be changed in every file with the upcoming housekeeping PR?

2021-09-24 13:57 UTC, schroedtert commented on src/main.cpp
> +                     "lib");
Do we need this?

2021-09-24 13:57 UTC, schroedtert commented on src/ThreadVisualisation.h
> +class ThreadVisualisation :public QObject {
Why the change from `QThread` to `QObject`? 
Maybe also a renaming of `ThreadVisualisation` should be considered, it is not a thread anymore, right?

2021-09-24 13:57 UTC, schroedtert commented on src/MainWindow.cpp
> +                    "Usage: jpsvis [file1] [-2D] [-caption] [-online [port]]");
Is `-online [port]` still supported?

2021-09-25 18:06 UTC, Ozaq commented on src/InteractorStyle.h
> +#pragma once
Yes I would like to do this for all files at some point.

2021-09-25 18:06 UTC, Ozaq commented on src/main.cpp
> +                     "lib");
Not sure if this is needed to find dependencies in installed packages, hence I left it until I had time to check further.

2021-09-25 18:12 UTC, Ozaq commented on src/ThreadVisualisation.h
> +class ThreadVisualisation :public QObject {
The change from `QThread` to `QObject` was done because this is no longer spawning a thread but still exposing signals and slots. I would like to distribute the contents of the class into different ones. But I think your right, even if it is just for some time, the class should be renamed. Ill rename it to `Visualisation` not good but at least it does no longer imply it would be a thread.

2021-09-25 18:18 UTC, Ozaq commented on src/MainWindow.cpp
> +                    "Usage: jpsvis [file1] [-2D] [-caption] [-online [port]]");
nope, will remove it

2021-09-26 04:08 UTC, chraibi commented
I think  VTK8's `GetRenderWindow()` was renamed in VTK9 to `renderWindow()`. See [diff](https://fossies.org/diffs/VTK/8.2.0_vs_9.0.0/GUISupport/Qt/QVTKOpenGLNativeWidget.h-diff.html)
and CI @8.2 is choking 
<img width="1118" alt="Screen Shot 2021-09-26 at 06 04 19" src="https://user-images.githubusercontent.com/5772973/134793302-833f166d-be72-498c-be2e-b04d3b00cf12.png">

2021-09-26 05:02 UTC, chraibi commented
Windows do not like `Log.h`s definition of `ERROR`, since this constant is already defined somewhere else. 
Therefore, this suggestion [her](https://www.dropbox.com/s/bsdfx81pus1n4jt/Undef_Windows_defined_ERROR_.patch?dl=0).

2021-09-26 05:05 UTC, chraibi requested changes
Great PR and thanks for your efforts. See comments!

2021-09-26 06:16 UTC, chraibi reviewed
I think you might remove this [osx-fix](https://github.com/JuPedSim/jpsvis/tree/master/src/fix) as well.

2021-09-26 11:06 UTC, Ozaq commented
@chraibi
* Removed os_fix
* pushed a fix attempt for the error macro
* added compute file for vtk8/9

We will see how may more API changes are present in vtk.

2021-09-26 13:14 UTC, chraibi commented on CMakeLists.txt
> +        $<$<CXX_COMPILER_ID:MSVC>:WIN32_LEAN_AND_MEAN>
It´s a kind of magic! :-)

2021-09-26 13:14 UTC, chraibi commented on src/VtkVersionSwitch.h
> +/// This file provides wrapper functions around breakage in VTK API versions.
Sauber!

2021-09-26 13:15 UTC, chraibi approved these changes
builds succesfully on windows.

2021-09-26 14:19 UTC, Ozaq commented
@chraibi and @schroedtert I took the liberty to resolve all comments, I did address all your points.

2021-09-26 14:19 UTC, merged